Complete ror task 2
plastmastick/TestGuru pull request #1
Opened 2022-04-21 12:15 UTC by plastmastick

https://thinknetica.teachbase.ru/course_sessions/429694/tasks/9168/take?return_url=/viewer/sessions/429694/tasks/9168

1. Добавьте в конфигурацию Rails приложения своё местоположение: часовой пояс и язык
2. Добавьте Initializer с версией приложения. Для этого добавьте файл version.rb с нужным кодом в config/initilizers/
3. Добавьте статическую страницу /about с кратким описанием проекта, включая ссылку на сайт онлайн-школы Thinknetica (http://www.thinknetica.com/)
4. Добавьте статическую страницу /about/author с информацией об авторе (включая ссылку на GitHub профиль)
5. Добавьте в README.md список сущностей (объектов реального мира) для проекта TestGuru

2022-04-21 17:08 UTC, VidgarVii requested changes

2022-04-21 17:08 UTC, VidgarVii commented on config/initializers/version.rb
> +end
далеко не самый лучший подход. 
Задача дать версию проекту. 
Название проекта TestGuru
Значит в моделе TestGuru и еще лучше приложению TestGuru
TestGuru::Application стоит определить константу VERSION с текущей версией ПО.
Сейчас есть просто модуль VERSION который не понятно к чему относится.

И 3 констаны в массиве, вызов методов. Определение STRING это всё лишние операции, которые просто в пустую тратят ресурсы компьютера. 
Можно же просто в константу положить строку. И всё.

2022-04-21 17:08 UTC, VidgarVii commented on public/about/author.html
> +  <p>Github: https://github.com/plastmastick</p>
тот же замечание

2022-04-21 17:08 UTC, VidgarVii commented on public/about/author.html
> +</html>
хорошо бы что бы на эту страницу тоже была ссылка из public/about.html. И на оборот

2022-04-22 09:25 UTC, plastmastick commented on README.md
> +  - Answers
Добавил недостающие сущности (Категория и Результат).
Или имелось в виду, что нужно вставлять сценарий вместо сущностей?

2022-04-22 09:27 UTC, plastmastick commented on config/initializers/version.rb
> +end
Если я правильно понял, то нужно в version.rb оставить только константу.
При выполнении Rails.application.initialize! она будет инициализирована в TestGuru::Application
Верно?

2022-04-22 09:27 UTC, plastmastick commented on public/about.html
> +  <p>Сайт: http://www.thinknetica.com/</p>
Сделал

2022-04-22 09:27 UTC, plastmastick commented on public/about/author.html
> +  <p>Github: https://github.com/plastmastick</p>
Сделал

2022-04-22 09:27 UTC, plastmastick commented on public/about/author.html
> +</html>
Сделал

2022-04-22 10:22 UTC, VidgarVii requested changes

2022-04-22 10:22 UTC, VidgarVii commented on README.md
> +  - Teachers
учителей не будет

2022-04-22 10:22 UTC, VidgarVii commented on README.md
> +  - Students
Студентов тоже. Можно просто абстрагироваться и назвать сущность User

2022-04-22 10:22 UTC, VidgarVii commented on README.md
> +  - Answers
только сущности

2022-04-22 10:22 UTC, VidgarVii commented on config/initializers/version.rb
> +VERSION = "0.1.0"
самое важное пропустил

> Значит в модуле TestGuru и еще лучше приложению TestGuru
> TestGuru::Application стоит определить константу VERSION с текущей версией ПО.
> Сейчас есть просто модуль VERSION который не понятно к чему относится

2022-04-22 10:22 UTC, VidgarVii commented on config/initializers/version.rb
> +VERSION = "0.1.0"
"мутабельные" объекты (строки, хэши, массивы) рекомендуется `freeze`-ить, чтобы они были неизменяемыми
в противном случае константу, ссылающуюся на "мутабельный" объект,  можно изменить: `VERSION << '3.14..'`

2022-04-22 10:22 UTC, VidgarVii commented on public/about.html
> +    <a href="/about/author" rel="nofollow" rel="noopener">
внутренние ссылки сайта не стоит блокировать поисковому роботу

2022-04-22 10:22 UTC, VidgarVii commented on public/about.html
> +    <a href="http://www.thinknetica.com/" target="_blank" rel="nofollow" rel="noopener">
https://thinknetica.com/

2022-04-22 13:40 UTC, plastmastick commented on config/initializers/version.rb
> +VERSION = "0.1.0"
Style/RedundantFreeze: Do not freeze immutable objects, as freezing them has no effect.
rubocop ругается на .freeze, если я правильно понял, то в ruby 3.0 константы фризяться автоматически. Изменить значение как было вами указано не получилось: https://gist.github.com/plastmastick/ad0f9260481e84ab1f63a39ae72a588e

2022-04-22 20:35 UTC, VidgarVii commented on config/initializers/version.rb
> +VERSION = "0.1.0"
константы автоматически не фризятся
Константа это все-лишь способ хранения информации.
А вот будет ли эта информация замороженая зависит от типа данных.
может в косноле по пробовать по вызывать .frozen?
У тебя в файле есть комментарий # frozen_string_literal: true
Вот он фризит все данные во всём файле. Исключение массивы и хеши.
По этому .freeze безполезен когда есть # frozen_string_literal: true

2022-04-23 08:02 UTC, plastmastick commented on config/initializers/version.rb
> +VERSION = "0.1.0"
Понял, большое спасибо

2022-04-26 16:11 UTC, merged