Часть 11. Аутентификация с Devise
plastmastick/TestGuru pull request #10
Opened 2022-07-23 22:16 UTC by plastmastick

1. Реализуйте аутентификацию в проекте при помощи библиотеки Devise
2. Сделайте управление ресурсами вопросов и ответов доступным только для администраторов
3. С помощью хэлпера Devise реализуйте перенаправление администраторов на страницу /admin/tests после логина
4. При создании нового теста администратором назначайте его в качестве автора теста

Усложненное задание:

При регистрации пользователя запрашивать его имя и фамилию и после входа, выводить флэш-сообщение "Привет, <имя пользователя>!"

2022-07-24 05:47 UTC, VidgarVii requested changes

2022-07-24 05:47 UTC, VidgarVii commented on app/controllers/admin/base_controller.rb
> +
в этом контроллере стоит еще проверить, что админ вообще был залогинен

2022-07-24 05:47 UTC, VidgarVii commented on app/controllers/admin/tests_controller.rb
> +  def start
экшен `start` в контроллере админа не нужен
это функционал пользователя

2022-07-24 05:47 UTC, VidgarVii commented on app/controllers/admin/tests_controller.rb
> +    @test.author = current_user
тут что-то сложное очень
авторство задается через ассоциации - подумай как это сделать

подсказка: автор - текущий пользователь, у модели Юзер есть связь с Тестами как раз для обозначения авторства

2022-07-24 05:47 UTC, VidgarVii commented on app/controllers/application_controller.rb
>    end
не совсем понятно, зачем это всё? Какую пользу хочешь получить от этих всех махинаций?

2022-07-24 05:47 UTC, VidgarVii commented on app/helpers/application_helper.rb
> +      end
render внутри each очень плохая идея. Работает медленно

2022-07-24 05:47 UTC, VidgarVii commented on app/helpers/application_helper.rb
>  end
будет удобней если в вью мы будет запрашивать сообщение определённого типа.
Так сможем для примера алерты показывать наверху страницы. А другие сообщения внизу. Или по другому

2022-07-24 05:47 UTC, VidgarVii commented on app/helpers/application_helper.rb
> +      messages.each do |m|
тут больше подошел бы метод map, чтобы не городить такие конструкции как 
rendered = []
flash.each
end
rendered

2022-07-26 06:48 UTC, VidgarVii requested changes

2022-07-26 06:48 UTC, VidgarVii commented on app/controllers/admin/tests_controller.rb
> +  before_action :set_test, only: %i[show edit update destroy start]
экшен start ни куда не делся

2022-07-26 06:48 UTC, VidgarVii commented on app/controllers/admin/tests_controller.rb
> +    current_user.author_tests.push(@test)
не совсем понятно зачем это, можно ведь проще
`current_user.author_tests.build(test_params)`

2022-07-26 06:48 UTC, VidgarVii commented on app/controllers/application_controller.rb
>    end
мне до сих пор не понятно что тут происходит) Отпиши мне в лс. Зачем это тут всё. Выглядит очень страшно
Если пытался решить задание с хелпером флеш сообщений. То во 1 хелперы в контроллерах не пишут
Во 2. Подразумевается что нужен метод который будет возвращать хтмл верстку с одним определённым типом сообщения

2022-07-26 06:48 UTC, VidgarVii commented on app/controllers/tests_controller.rb
> +  before_action :set_test, only: %i[start]
для 1 экшена колбек не объявляют. Это усложняет код и дебажить будет сложнее

2022-07-26 06:48 UTC, VidgarVii commented on app/helpers/application_helper.rb
> +  end
тоже сомнительные метод

2022-07-26 06:48 UTC, VidgarVii commented on app/views/admin/_nav.html.erb
> +</div>
No new lina at end of file
такого не должно быть в коде

2022-07-26 19:01 UTC, VidgarVii requested changes

2022-07-26 19:01 UTC, VidgarVii commented on app/views/shared/_flash.html.erb
> +<%= render_messages(:info) %>
стоило вообще удалить этот файл. И показывать флеш сообщение только там где это нужно или использовать yield(key)
http://rusrails.ru/layouts-and-rendering#ponimanie-yield

2022-07-27 07:33 UTC, plastmastick commented on app/controllers/users/sessions_controller.rb
> +    super
а разница какая, если у меня ключ не дефолтный?
Оно и так отображается.

2022-07-27 07:35 UTC, plastmastick commented on app/controllers/application_controller.rb
>    end
А если мне нужно вывести за один раз несколько флэш сообщений одного типа?
А возможно и из разных мест?

2022-07-27 07:50 UTC, plastmastick commented on app/controllers/users/sessions_controller.rb
> +    super
исправил

2022-07-27 07:50 UTC, plastmastick commented on app/controllers/application_controller.rb
>    end
убрал

2022-07-27 15:02 UTC, merged