Task 15. "JavaScript в Rails-приложении"
plastmastick/TestGuru pull request #14
Opened 2022-08-27 16:04 UTC by plastmastick

- Добавьте сортировку по заголовку теста для таблицы отображения тестов доступных пользователю для прохождения

- Используя событие input проверяйте совпадение пароля и его подтверждения на странице регистрации пользователя. 
Пока значения не совпадают информируйте об этом пользователя (например выводя иконку красного цвета). Информируйте также пользователя в том случае когда значения совпадают (например выводя иконку зелёного цвета). Не информируйте пользователя если поле подтверждения пароля не содержит значения

2022-08-28 17:26 UTC, VidgarVii requested changes

2022-08-28 17:26 UTC, VidgarVii commented on app/javascript/utilities/input_check.js
> +    var checkFields = document.querySelectorAll('.password-check')
Время глобальных var-ов прошло. при объявлении переменных используй let/const. Так безопасней и код становиться понятней. Обязательно по гугли отличие!

2022-08-28 17:26 UTC, VidgarVii commented on app/javascript/utilities/input_check.js
> +}
лучше потренироваться в ООП. JS позволяет создавать классы и браузеры это понимают, пусть пока и без инкапсуляций, но уже хоть что-то.
По пробуй создать такой класс утилиту, который принимает html элемент. И далее пусть эта утилита работает только с этим элементов. Таким образом мы сможем пере использоваться утилиту сколько угодно раз с разными элементами без переписывания кода. И так вся логика функционала будет обёрнута в класс, а не просто болтаться где-то снаружи. 
http://old.code.mu/books/javascript/oop/

2022-08-28 17:27 UTC, VidgarVii requested changes

2022-08-28 17:27 UTC, VidgarVii commented on app/assets/stylesheets/application.scss
> +@import 'global';
в конце файла надо отставлять 1 пустую строчку. Это указатель на конец файла. Сейчас система думает, что происходит обрыв файла. Даже гитхаб ругается. No new lina at end of file

2022-08-28 17:27 UTC, VidgarVii commented on app/javascript/utilities/input_check.js
> +    // https://developer.mozilla.org/ru/docs/Web/API/NodeList
этот комментарий не несёт ни какой пользы

2022-08-28 17:27 UTC, VidgarVii commented on app/javascript/utilities/sorting.js
> +}
тут всё тоже самое

2022-08-30 08:35 UTC, plastmastick commented on app/assets/stylesheets/application.scss
> +@import 'global';
поправил и настроил idea

2022-08-31 07:35 UTC, VidgarVii requested changes

2022-08-31 07:35 UTC, VidgarVii commented on app/javascript/utilities/manipulator.js
> +document.addEventListener('turbolinks:load', function () {
определять класс можно и лучше без использования document.addEventListener('turbolinks:load
А вот создавать экземпляр класса и его использовать внутри document.addEventListener('turbolinks:load

2022-08-31 07:35 UTC, VidgarVii commented on app/javascript/utilities/manipulator.js
> +        }
получился божественный, грязный, большой класс, который не совсем понятно чем занимается.
В ПР 2 функционала. Сортировка и проверка паролей. Должно получиться 2 класса.

2022-08-31 07:35 UTC, VidgarVii commented on app/javascript/utilities/manipulator.js
> +            let passwordConfirmation = document.querySelector('input#user_password_confirmation')
на каждое срабатывание событие происходит поиск элементов. Когда можно это делать 1 раз и не мучить ресурсы компьютера клиента

2022-08-31 07:35 UTC, VidgarVii commented on app/javascript/utilities/manipulator.js
> +        sortRowsByTitle = () => {
методы пишут так 
```
sortRowsByTitle() {
}
```

2022-08-31 07:35 UTC, VidgarVii commented on app/javascript/utilities/manipulator.js
> +            let tbody = document.querySelector('tbody')
если переменная не переопределяется, то принято считать её константой. Так безопасней

2022-09-01 07:12 UTC, merged