Часть 3. Задание по основам Rails-моделей
plastmastick/TestGuru pull request #2
Opened 2022-04-28 16:50 UTC by plastmastick

https://thinknetica.teachbase.ru/course_sessions/429694/tasks/9170/take

1. Создайте Rails-модели с нужными атрибутами для следующих сущностей:

- Тест
- Вопрос
- Ответ
- Пользователь
- Категория

2. С помощью механизма миграций, добавьте ограничения целостности на уровне БД в соответствующих таблицах для необходимых атрибутов так, чтобы они не могли содержать значение NULL

3. С помощью механизма миграций добавьте значения по умолчанию:

- Для уровня Теста
- Для атрибута correct у Ответа

Дополнительно:
Настроил rubocop, внес правки (коммиты style:..)

2022-04-28 17:16 UTC, VidgarVii requested changes

2022-04-28 17:16 UTC, VidgarVii commented on db/migrate/20220428114453_add_answers_correct_default_value.rb
> +  end
сегодня в чате обсуждали 
не стоит добавлять отдельные миграции для изменения полей в одном ПР. Миграции всегда являются опасным местом в ПО. Так как меняют схему базы. И всегда стараются минимизировать кол-во миграций.
В этом ДЗ надо создать 5 моделей и 5 таблиц. Значит у тебя должно быть 5 миграций. Прописывай все нужные опции полям сразу. Все остальные миграции являются обычным оверхедом

Пример
```
t.string :title, null: false 
```
Большое кол-во миграций увеличивает время развёртывания ПО. Так же миграция является местом риска, так как может сломать существующую базу. Еще они имеют свойство протухать и быть не актуальными или не рабочими. По этому всегда стараются минимизировать кол-во миграций.

2022-04-28 17:16 UTC, VidgarVii commented on db/migrate/20220427192500_create_tests.rb
> +      t.integer :category_id
нужны не просто поля, а [внешние ключи](https://en.wikipedia.org/wiki/Foreign_key)

чтобы добавить `FOREIGN KEY constraint` нужно миграцию записать так:
```ruby
t.references :category, foreign_key: true, null: false

2022-04-28 17:16 UTC, VidgarVii commented on db/migrate/20220427192500_create_tests.rb
> +      t.integer :category_id
для теста нам еще понадобиться автор. Это юзер который создал тест. Давай сделаем это в текущем ПР

2022-04-28 17:57 UTC, plastmastick commented on db/migrate/20220428114453_add_answers_correct_default_value.rb
> +  end
Блин, а я ещё насоздавал, буду править тогда)

2022-04-28 18:34 UTC, plastmastick commented on db/migrate/20220427192500_create_tests.rb
> +      t.integer :category_id
https://github.com/plastmastick/TestGuru/pull/2/commits/ba037e79cc77ee93d0fdec8df2c85c6cc330b252

2022-04-28 18:35 UTC, plastmastick commented on db/migrate/20220428114453_add_answers_correct_default_value.rb
> +  end
https://github.com/plastmastick/TestGuru/pull/2/commits/ba037e79cc77ee93d0fdec8df2c85c6cc330b252

2022-04-29 06:36 UTC, VidgarVii requested changes

2022-04-29 06:36 UTC, VidgarVii commented on db/migrate/20220428105750_create_answers.rb
> +      t.boolean :correct, default: false
для логических полей рекомендуется указывать опцию `null: false`
тогда в базе будут возможны строго два значения `true` или `false` вместо трех (`null/true/false`)

2022-04-29 06:36 UTC, VidgarVii commented on db/migrate/20220427192500_create_tests.rb
> +      t.references :author, foreign_key: true, null: false
внешний ключ будет ссылаться на таблицу authors поле id. И будет ошибка. 
Но у нас нет таблицы авторы. Надо чтобы ключ смотрел в таблицу юзеры. 
Советую переключиться на PostgreSQL. Тогда ошибки увидишь еще на момент создания миграций.
Все опции смотри тут 
https://apidock.com/rails/ActiveRecord/ConnectionAdapters/SchemaStatements/add_reference

2022-04-29 06:36 UTC, VidgarVii commented on db/migrate/20220427192500_create_tests.rb
> +      t.integer :level, default: 1
null: false

2022-04-29 09:59 UTC, plastmastick commented on db/migrate/20220427192500_create_tests.rb
> +      t.integer :level, default: 1
исправил

2022-04-29 10:00 UTC, plastmastick commented on db/migrate/20220427192500_create_tests.rb
> +      t.references :author, foreign_key: true, null: false
Установил, по возможности чекните корректность смены адаптера

2022-04-29 10:00 UTC, plastmastick commented on db/migrate/20220428105750_create_answers.rb
> +      t.boolean :correct, default: false
исправил

2022-04-29 16:31 UTC, VidgarVii requested changes

2022-04-29 16:31 UTC, VidgarVii commented on config/database.yml
> +  password: test_guru
host, логины и пароли не должны попадать в репозиторий. И они могут отличаться
Хороший практикой будет положить файл database.yml в .gitignore
А в репозиторий залить  database.yml.sample с пустыми логином и паролем.

2022-04-29 16:31 UTC, VidgarVii commented on db/migrate/20220427192500_create_tests.rb
> +      t.references :user, foreign_key: true, null: false
При проектировании таблиц надо учитывать смысловую нагрузку.
Лучше если поле в таблице будет называться author_id.
Так как по логике нам надо создать связь теста с юзером как автор теста
т.е. должно получиться
t.references :author... 
Но учти чтоб внешний ключ смотрел на таблицу юзеров
Все опции смотри тут 
https://apidock.com/rails/ActiveRecord/ConnectionAdapters/SchemaStatements/add_reference

2022-05-03 08:58 UTC, merged