Часть 5. Ассоциации моделей
plastmastick/TestGuru pull request #4
Opened 2022-05-10 17:33 UTC by plastmastick

1. Создайте ER-диаграмму проекта TestGuru, основываясь на сущностях моделей которые были определены в предыдущем задании. Разместите её на странице GitHub вашего репозитория в разделе GitHub wiki. В качестве инструмента рекомендуется использовать [draw.io](https://draw.io/)

2. Определите ассоциации в моделях:

- Между Тестами и Категориями
- Между Тестами и Вопросами
- Между Вопросами и Ответами
- Между Тестами и проходящими их Пользователями (учесть, что один и тот же тест могут проходить несколько пользователей одновременно)
- Между Тестом и автором (Пользователем), который его создал.

2022-05-11 06:44 UTC, VidgarVii requested changes

2022-05-11 06:44 UTC, VidgarVii commented on app/models/question.rb
> +  belongs_to :test
belongs_to и has_many разделяют пустыми строками. Такое разделение кода на логические блоки.
Пример оформления модели можно посмотреть тут https://github.com/rubocop/rails-style-guide#macro-style-methods

2022-05-11 06:44 UTC, VidgarVii commented on app/models/question.rb
> +  belongs_to :test
Еще одно нарушение style guide
Надо соблюдай очередность.
Принято сначала писать belongs_to далее ниже has_
Так мы будем понимать какой код где находится

2022-05-11 06:44 UTC, VidgarVii commented on app/models/category.rb
> +  has_many :tests, dependent: nil
очень сомнительный выбор варианта dependent
Протестируй удаление категории, теста и т.д.
Удаление должно происходить рекурсивно без ошибок

2022-05-11 06:44 UTC, VidgarVii commented on app/models/test.rb
> +  belongs_to :user, foreign_key: :author_id, inverse_of: :tests
по логике тут нужен автор. В таблице эту логику сохранили. А в модели почему сломали?

2022-05-11 06:44 UTC, VidgarVii commented on app/models/test.rb
> +  belongs_to :user, foreign_key: :author_id, inverse_of: :tests
нет связи с пользователями проходившие тест

2022-05-11 06:44 UTC, VidgarVii commented on app/models/test.rb
>      Test.joins('JOIN categories ON tests.category_id = categories.id')
с использованием ассоциации `joins` можно сильно сократить
в задании "Ассоциации моделей" самое время это сделать

***
```ruby
  joins(:category)
    .where(categories: { title: category_title })
    .order(title: :desc)
    .pluck(:title)
```

2022-05-11 06:44 UTC, VidgarVii commented on app/models/user.rb
> +  has_many :tests, foreign_key: :author_id, dependent: nil, inverse_of: :user
все замечания те же, что в модели Тест

2022-05-11 06:44 UTC, VidgarVii commented on db/seeds.rb
> +    { body: 'Какой тэг используется для обозначения ссылок?', test_id: tests[2].id }
теперь, благодаря ассоциациям, можно (и рекомендуется в ООП) передавать объекты для связывания по ключам, вместо аттрибутов: `category: categories[0]`, `author: users[0]` и т.п. (без `_id` , `.id`)

2022-05-11 12:37 UTC, plastmastick commented on app/models/category.rb
> +  has_many :tests, dependent: nil
Проставил везде :destroy, при удалении теперь рекурсивно удаляются все связанные объекты. Оставил только для User.author_tests nil, т.к. не правильно удалять тест, который может кто-то другой проходить из-за отсутствия автора в системе

2022-05-12 06:03 UTC, VidgarVii requested changes

2022-05-12 06:03 UTC, VidgarVii commented on app/models/user.rb
> +                          dependent: nil, inverse_of: :author
dependent: nil
по логике вполне ожидаемый вариант. Но текущая схема базы и ER схема с тобой не согласятся. Перепроверяй свой код!

2022-05-12 07:26 UTC, plastmastick commented on app/models/test.rb
> +    Test.joins(:category)
А нельзя сделать без joins? 
category.where(...).order(...).pluck(...)

Или это менее читаемо?

2022-05-12 07:26 UTC, plastmastick commented on app/models/user.rb
> +                          dependent: nil, inverse_of: :author
Обновил схемы

2022-05-12 15:11 UTC, VidgarVii commented on app/models/test.rb
> +  belongs_to :author, class_name: "User", inverse_of: :author_tests
ассоциация говорит, что автор должен быть.
стоит тогда добавить опцию optional: true

http://rusrails.ru/active-record-associations#optional

2022-05-12 15:13 UTC, VidgarVii commented on app/models/user.rb
> +                          dependent: nil, inverse_of: :author
dependent: nil
нил даже в документации нет
правильней nullify
http://rusrails.ru/active-record-associations#dependent3

2022-05-12 16:25 UTC, plastmastick commented on app/models/user.rb
> +                          dependent: nil, inverse_of: :author
Такое значение есть, оно дефолтное https://api.rubyonrails.org/classes/ActiveRecord/Associations/ClassMethods.html#method-i-has_one

Согласен, что логичнее будет сделать  nullify

2022-05-12 17:58 UTC, merged